return {
    type = "animation_editor",
    format = "json",
    data = {
        animations = {
            {
                duration = 4,
                animation_keys = {
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.31,
                        key_type = "tween",
                        property_id = "color_g",
                        node_id = "wall1#sprite",
                        duration = 0.85,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.67,
                        key_type = "tween",
                        property_id = "color_b",
                        node_id = "wall1#sprite",
                        duration = 0.85,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.77,
                        key_type = "tween",
                        property_id = "color_r",
                        node_id = "wall1#sprite",
                        duration = 0.85,
                    },
                    {
                        easing = "outsine",
                        start_value = 320,
                        end_value = 128,
                        key_type = "tween",
                        property_id = "position_y",
                        node_id = "wall1",
                        duration = 1,
                    },
                    {
                        easing = "outsine",
                        start_value = 320,
                        end_value = 512,
                        key_type = "tween",
                        property_id = "position_y",
                        node_id = "wall",
                        duration = 1,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.3,
                        key_type = "tween",
                        property_id = "color_r",
                        node_id = "wall#sprite",
                        duration = 1.06,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.33,
                        key_type = "tween",
                        property_id = "color_b",
                        node_id = "wall#sprite",
                        duration = 1.06,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.73,
                        key_type = "tween",
                        property_id = "color_g",
                        node_id = "wall#sprite",
                        duration = 1.06,
                    },
                    {
                        easing = "outsine",
                        end_value = -20,
                        key_type = "tween",
                        property_id = "rotation_z",
                        node_id = "camera",
                        duration = 1.1,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 1.3,
                        key_type = "tween",
                        property_id = "scale_x",
                        node_id = "camera",
                        duration = 1.1,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 1.3,
                        key_type = "tween",
                        property_id = "scale_y",
                        node_id = "camera",
                        duration = 1.1,
                    },
                    {
                        easing = "outsine",
                        start_value = 480,
                        end_value = 275,
                        key_type = "tween",
                        property_id = "position_x",
                        node_id = "camera",
                        duration = 1.1,
                    },
                    {
                        easing = "inoutsine",
                        start_value = 832,
                        end_value = 127,
                        key_type = "tween",
                        property_id = "position_x",
                        node_id = "wall2",
                        duration = 2,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 256,
                        end_value = 512,
                        node_id = "wall2#sprite",
                        property_id = "size_x",
                        start_time = 0.15,
                        duration = 0.83,
                    },
                    {
                        node_id = "wall2#sprite",
                        start_value = 32,
                        key_type = "tween",
                        easing = "outsine",
                        property_id = "slice9_right",
                        start_time = 0.23,
                        duration = 0.98,
                    },
                    {
                        easing = "linear",
                        key_type = "animation",
                        start_time = 0.33,
                        property_id = "test",
                        data = "test",
                        duration = 1,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.77,
                        end_value = 0.31,
                        node_id = "wall1#sprite",
                        property_id = "color_r",
                        start_time = 0.85,
                        duration = 1.57,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.67,
                        end_value = 0.35,
                        node_id = "wall1#sprite",
                        property_id = "color_b",
                        start_time = 0.85,
                        duration = 1.57,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.31,
                        end_value = 0.77,
                        node_id = "wall1#sprite",
                        property_id = "color_g",
                        start_time = 0.85,
                        duration = 1.57,
                    },
                    {
                        key_type = "tween",
                        easing = "outquad",
                        start_value = 512,
                        end_value = 256,
                        node_id = "wall2#sprite",
                        property_id = "size_x",
                        start_time = 0.98,
                        duration = 0.95,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 512,
                        end_value = 127,
                        node_id = "wall",
                        property_id = "position_y",
                        start_time = 1,
                        duration = 2,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 128,
                        end_value = 512,
                        node_id = "wall1",
                        property_id = "position_y",
                        start_time = 1,
                        duration = 2,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.73,
                        end_value = 0.3,
                        node_id = "wall#sprite",
                        property_id = "color_g",
                        start_time = 1.06,
                        duration = 1.75,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.3,
                        end_value = 0.51,
                        node_id = "wall#sprite",
                        property_id = "color_r",
                        start_time = 1.06,
                        duration = 1.75,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.33,
                        end_value = 0.73,
                        node_id = "wall#sprite",
                        property_id = "color_b",
                        start_time = 1.06,
                        duration = 1.75,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 275,
                        end_value = 480,
                        node_id = "camera",
                        property_id = "position_x",
                        start_time = 1.1,
                        duration = 2.28,
                    },
                    {
                        node_id = "camera",
                        start_value = -20,
                        key_type = "tween",
                        easing = "outsine",
                        property_id = "rotation_z",
                        start_time = 1.1,
                        duration = 2.9,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 1.3,
                        end_value = 1,
                        node_id = "camera",
                        property_id = "scale_x",
                        start_time = 1.1,
                        duration = 2.9,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 1.3,
                        end_value = 1,
                        node_id = "camera",
                        property_id = "scale_y",
                        start_time = 1.1,
                        duration = 2.9,
                    },
                    {
                        easing = "insine",
                        key_type = "tween",
                        end_value = 32,
                        node_id = "wall2#sprite",
                        property_id = "slice9_right",
                        start_time = 1.21,
                        duration = 0.8,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 32,
                        end_value = 10,
                        node_id = "wall2#sprite",
                        property_id = "slice9_left",
                        start_time = 1.96,
                        duration = 0.98,
                    },
                    {
                        key_type = "tween",
                        easing = "inoutsine",
                        start_value = 127,
                        end_value = 832,
                        node_id = "wall2",
                        property_id = "position_x",
                        start_time = 2,
                        duration = 2,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 256,
                        end_value = 512,
                        node_id = "wall2#sprite",
                        property_id = "size_x",
                        start_time = 2.19,
                        duration = 0.71,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.35,
                        end_value = 1,
                        node_id = "wall1#sprite",
                        property_id = "color_b",
                        start_time = 2.42,
                        duration = 1.58,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.77,
                        end_value = 1,
                        node_id = "wall1#sprite",
                        property_id = "color_g",
                        start_time = 2.42,
                        duration = 1.58,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.31,
                        end_value = 1,
                        node_id = "wall1#sprite",
                        property_id = "color_r",
                        start_time = 2.42,
                        duration = 1.58,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.73,
                        end_value = 1,
                        node_id = "wall#sprite",
                        property_id = "color_b",
                        start_time = 2.81,
                        duration = 1.19,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.3,
                        end_value = 1,
                        node_id = "wall#sprite",
                        property_id = "color_g",
                        start_time = 2.81,
                        duration = 1.19,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 0.51,
                        end_value = 1,
                        node_id = "wall#sprite",
                        property_id = "color_r",
                        start_time = 2.81,
                        duration = 1.19,
                    },
                    {
                        key_type = "tween",
                        easing = "outquad",
                        start_value = 512,
                        end_value = 256,
                        node_id = "wall2#sprite",
                        property_id = "size_x",
                        start_time = 2.9,
                        duration = 0.91,
                    },
                    {
                        key_type = "tween",
                        easing = "outsine",
                        start_value = 10,
                        end_value = 32,
                        node_id = "wall2#sprite",
                        property_id = "slice9_left",
                        start_time = 2.93,
                        duration = 0.92,
                    },
                    {
                        key_type = "tween",
                        easing = "insine",
                        start_value = 127,
                        end_value = 320,
                        node_id = "wall",
                        property_id = "position_y",
                        start_time = 3,
                        duration = 1,
                    },
                    {
                        key_type = "tween",
                        easing = "insine",
                        start_value = 512,
                        end_value = 320,
                        node_id = "wall1",
                        property_id = "position_y",
                        start_time = 3,
                        duration = 1,
                    },
                },
                animation_id = "level",
            },
            {
                duration = 1,
                animation_keys = {
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.8,
                        key_type = "tween",
                        property_id = "scale_x",
                        node_id = "wall",
                        duration = 0.25,
                    },
                    {
                        easing = "outsine",
                        start_value = 1,
                        end_value = 0.8,
                        key_type = "tween",
                        property_id = "scale_y",
                        node_id = "wall",
                        duration = 0.25,
                    },
                    {
                        key_type = "tween",
                        easing = "outback",
                        start_value = 0.8,
                        end_value = 1,
                        node_id = "wall",
                        property_id = "scale_x",
                        start_time = 0.25,
                        duration = 0.34,
                    },
                    {
                        key_type = "tween",
                        easing = "outback",
                        start_value = 0.8,
                        end_value = 1,
                        node_id = "wall",
                        property_id = "scale_y",
                        start_time = 0.25,
                        duration = 0.34,
                    },
                },
                animation_id = "test",
            },
        },
        metadata = {
            layers = {
            },
            gizmo_steps = {
            },
            fps = 60,
            gui_path = "/example/movement/movement.collection",
            settings = {
                font_size = 40,
            },
        },
        nodes = {
        },
    },
    version = 1,
}