return {
    format = "json",
    type = "animation_editor",
    version = 1,
    data = {
        nodes = {
        },
        metadata = {
            fps = 60,
            layers = {
            },
            settings = {
                font_size = 40,
            },
            gizmo_steps = {
            },
            gui_path = "/example/movement/movement.collection",
        },
        animations = {
            {
                duration = 4,
                animation_id = "level",
                animation_keys = {
                    {
                        start_value = 1,
                        duration = 0.85,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.309,
                        node_id = "wall1#sprite",
                        property_id = "color_g",
                    },
                    {
                        start_value = 1,
                        duration = 0.85,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.67,
                        node_id = "wall1#sprite",
                        property_id = "color_b",
                    },
                    {
                        start_value = 1,
                        duration = 0.85,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.772,
                        node_id = "wall1#sprite",
                        property_id = "color_r",
                    },
                    {
                        start_value = 256,
                        duration = 0.98,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 512,
                        node_id = "wall2#sprite",
                        property_id = "size_x",
                    },
                    {
                        start_value = 320,
                        duration = 1,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 128,
                        node_id = "wall1",
                        property_id = "position_y",
                    },
                    {
                        start_value = 320,
                        duration = 1,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 512,
                        node_id = "wall",
                        property_id = "position_y",
                    },
                    {
                        start_value = 1,
                        duration = 1.06,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.303,
                        node_id = "wall#sprite",
                        property_id = "color_r",
                    },
                    {
                        start_value = 1,
                        duration = 1.06,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.327,
                        node_id = "wall#sprite",
                        property_id = "color_b",
                    },
                    {
                        start_value = 1,
                        duration = 1.06,
                        easing = "outsine",
                        key_type = "tween",
                        end_value = 0.734,
                        node_id = "wall#sprite",
                        property_id = "color_g",
                    },
                    {
                        start_value = 832,
                        duration = 2,
                        easing = "inoutsine",
                        key_type = "tween",
                        end_value = 127,
                        node_id = "wall2",
                        property_id = "position_x",
                    },
                    {
                        start_value = 0.772,
                        duration = 1.57,
                        start_time = 0.85,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 0.309,
                        key_type = "tween",
                        property_id = "color_r",
                    },
                    {
                        start_value = 0.67,
                        duration = 1.57,
                        start_time = 0.85,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 0.346,
                        key_type = "tween",
                        property_id = "color_b",
                    },
                    {
                        start_value = 0.309,
                        duration = 1.57,
                        start_time = 0.85,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 0.772,
                        key_type = "tween",
                        property_id = "color_g",
                    },
                    {
                        start_value = 512,
                        duration = 1.21,
                        start_time = 0.98,
                        easing = "outquad",
                        node_id = "wall2#sprite",
                        end_value = 256,
                        key_type = "tween",
                        property_id = "size_x",
                    },
                    {
                        start_value = 512,
                        duration = 2,
                        start_time = 1,
                        easing = "outsine",
                        node_id = "wall",
                        end_value = 127,
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        start_value = 128,
                        duration = 2,
                        start_time = 1,
                        easing = "outsine",
                        node_id = "wall1",
                        end_value = 512,
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        start_value = 0.734,
                        duration = 1.75,
                        start_time = 1.06,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 0.303,
                        key_type = "tween",
                        property_id = "color_g",
                    },
                    {
                        start_value = 0.303,
                        duration = 1.75,
                        start_time = 1.06,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 0.513,
                        key_type = "tween",
                        property_id = "color_r",
                    },
                    {
                        start_value = 0.327,
                        duration = 1.75,
                        start_time = 1.06,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 0.734,
                        key_type = "tween",
                        property_id = "color_b",
                    },
                    {
                        start_value = 127,
                        duration = 2,
                        start_time = 2,
                        easing = "inoutsine",
                        node_id = "wall2",
                        end_value = 832,
                        key_type = "tween",
                        property_id = "position_x",
                    },
                    {
                        start_value = 256,
                        duration = 0.71,
                        start_time = 2.19,
                        easing = "outsine",
                        node_id = "wall2#sprite",
                        end_value = 512,
                        key_type = "tween",
                        property_id = "size_x",
                    },
                    {
                        start_value = 0.346,
                        duration = 1.58,
                        start_time = 2.42,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_b",
                    },
                    {
                        start_value = 0.772,
                        duration = 1.58,
                        start_time = 2.42,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_g",
                    },
                    {
                        start_value = 0.309,
                        duration = 1.58,
                        start_time = 2.42,
                        easing = "outsine",
                        node_id = "wall1#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_r",
                    },
                    {
                        start_value = 0.734,
                        duration = 1.19,
                        start_time = 2.81,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_b",
                    },
                    {
                        start_value = 0.303,
                        duration = 1.19,
                        start_time = 2.81,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_g",
                    },
                    {
                        start_value = 0.513,
                        duration = 1.19,
                        start_time = 2.81,
                        easing = "outsine",
                        node_id = "wall#sprite",
                        end_value = 1,
                        key_type = "tween",
                        property_id = "color_r",
                    },
                    {
                        start_value = 512,
                        duration = 1.1,
                        start_time = 2.9,
                        easing = "outquad",
                        node_id = "wall2#sprite",
                        end_value = 256,
                        key_type = "tween",
                        property_id = "size_x",
                    },
                    {
                        start_value = 127,
                        duration = 1,
                        start_time = 3,
                        easing = "insine",
                        node_id = "wall",
                        end_value = 320,
                        key_type = "tween",
                        property_id = "position_y",
                    },
                    {
                        start_value = 512,
                        duration = 1,
                        start_time = 3,
                        easing = "insine",
                        node_id = "wall1",
                        end_value = 320,
                        key_type = "tween",
                        property_id = "position_y",
                    },
                },
            },
        },
    },
}