return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                },
                duration = 1,
            },
            {
                animation_id = "appear",
                animation_keys = {
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_x",
                        start_value = 5,
                    },
                    {
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_y",
                        start_value = 5,
                    },
                    {
                        easing = "outsine",
                        end_value = 167,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 97,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "color_a",
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 87,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 167,
                    },
                    {
                        duration = 1.24,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_y",
                        start_value = 0.9,
                    },
                    {
                        duration = 1.92,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_x",
                        start_value = 0.9,
                    },
                    {
                        easing = "linear",
                        event_id = "appear_text",
                        key_type = "event",
                        property_id = "event",
                        start_time = 0.7,
                    },
                    {
                        duration = 0.26,
                        easing = "outsine",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "color_a",
                        start_time = 1,
                        start_value = 1,
                    },
                    {
                        duration = 0.99,
                        easing = "insine",
                        end_value = 97,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = 87,
                    },
                    {
                        duration = 0.62,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "color_a",
                        start_time = 1.37,
                        start_value = 1.3,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "disappear",
                animation_keys = {
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_x",
                        start_value = 5,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "scale_y",
                        start_value = 5,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 212,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 97,
                    },
                },
                duration = 0.3,
            },
            {
                animation_id = "anim1",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = -490,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_x",
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 187,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 97,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "anim2",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 152,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 97,
                    },
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 555,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_x",
                    },
                },
                duration = 1,
            },
            {
                animation_id = "anim3",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "outsine",
                        end_value = 7,
                        key_type = "tween",
                        node_id = "logo",
                        property_id = "position_y",
                        start_value = 97,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "examples/evo/game_object/gui_menu/gui_menu.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "gui",
                },
                {
                    color = "90D2F6",
                    name = "text",
                },
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}