return {
    type = "animation_editor",
    data = {
        metadata = {
            layers = {
            },
            fps = 60,
            settings = {
                font_size = 30,
            },
            gizmo_steps = {
            },
            gui_path = "/examples/boids/boid/boid_sensor.gui",
        },
        animations = {
            {
                animation_id = "default",
                duration = 1,
                animation_keys = {
                    {
                        duration = 0.5,
                        property_id = "rotation_z",
                        end_value = -90,
                        node_id = "pie",
                        start_value = -135,
                        key_type = "tween",
                        easing = "linear",
                    },
                    {
                        duration = 0.5,
                        property_id = "scale_x",
                        end_value = 1.5,
                        node_id = "pie",
                        start_value = 1,
                        key_type = "tween",
                        easing = "outsine",
                    },
                    {
                        duration = 0.5,
                        property_id = "scale_y",
                        end_value = 1.5,
                        node_id = "pie",
                        start_value = 1,
                        key_type = "tween",
                        easing = "outsine",
                    },
                    {
                        duration = 0.5,
                        property_id = "fill_angle",
                        end_value = 180,
                        node_id = "pie",
                        start_value = 270,
                        key_type = "tween",
                        easing = "linear",
                    },
                    {
                        start_time = 0.5,
                        duration = 0.5,
                        property_id = "rotation_z",
                        end_value = -135,
                        node_id = "pie",
                        start_value = -90,
                        key_type = "tween",
                        easing = "linear",
                    },
                    {
                        start_time = 0.5,
                        duration = 0.5,
                        property_id = "scale_x",
                        end_value = 1,
                        node_id = "pie",
                        start_value = 1.5,
                        key_type = "tween",
                        easing = "outsine",
                    },
                    {
                        start_time = 0.5,
                        duration = 0.5,
                        property_id = "scale_y",
                        end_value = 1,
                        node_id = "pie",
                        start_value = 1.5,
                        key_type = "tween",
                        easing = "outsine",
                    },
                    {
                        start_time = 0.5,
                        duration = 0.5,
                        property_id = "fill_angle",
                        end_value = 270,
                        node_id = "pie",
                        start_value = 180,
                        key_type = "tween",
                        easing = "linear",
                    },
                },
            },
        },
        nodes = {
        },
    },
    format = "json",
    version = 1,
}